### ISSUE TITLE
Any support for leaflet 0.8+ ?

### ISSUE THREAD

**Issue by zheffie** [makinacorpus/Leaflet.TextPath#23]

**Comment by leplatrem** [comment]
Did you try it ?

Maybe you could start a branch, we'll be happy to review and merge!

**Comment by zheffie** [comment]
Yes, I tried and it didn't work. I Don't have the time to dig in.

In any case, thank for your efforts and great plugin

**Comment by fredericbonifas** [comment]
@zheffie Could you please try the new branch `leaflet0.8-dev` and check if you see any problem with Leaflet 0.8 ? 

Thanks !

**Comment by zheffie** [comment]
Seems to be working :)

Thanks!
