### ISSUE TITLE
center: true option issue

### ISSUE THREAD

**Issue by bardu** [makinacorpus/Leaflet.TextPath#33]
We are building a mobile hiking app and on a couple of trails we noticed that setting 
```javascript
center: true
```
seems to have no effect, while it works on the other trails.
For the two trails where it is not working as supposed, I think the problem  is due to the fact that those trails have a cross section. This might result in a duplicated lat,lng pair in the polyline. Here is a screenshot:
![example](https://s3-us-west-2.amazonaws.com/pathmediabucket/images/IMG_0058.PNG)

**Comment by leplatrem** [comment]
Fixed by #34
