### ISSUE TITLE
Leaflet 1.0

### ISSUE THREAD

**Issue by bardu** [makinacorpus/Leaflet.TextPath#35]
Leaflet 1.0 is breaking your plugin, are there any plans to upgrade?

**Comment by fredericbonifas** [comment]
Did you try with the leaflet0.8-dev branch of the plugin?

**Comment by bardu** [comment]
This branch seems to work, thanks.

**Comment by plepe** [comment]
I can confirm that it works with leaflet 1.0.1. Why not rename the branch to `leaflet-1.0` or so? This would avoid confusion ...
