### ISSUE TITLE
Help: Adding labels

### ISSUE THREAD

**Issue by sundancemc** [makinacorpus/Leaflet.TextPath#36]
I need a little help, ok maybe a lot. The labels are not displaying on my map. I am trying to create a webpage with a large amount of polylines in several external GeoJSON files. Any advice or clues would be appreciated.

// sample code for website:
var centralsierra = $.getJSON("geojson/centralsierra.geojson")
    .then(function(data){
	L.geoJson(data, {
		style: function (feature) {
		        return {color: feature.properties.color};
		    },    
		onEachFeature: function (feature, layer) {
   		         layer.setText(feature.properties.NAME);
   		     },
        onEachFeature: function (feature, layer) {
        		layer.bindPopup('<b>Name:</b> ' + feature.properties.NAME + '<br >' +
                        '<b>Open:</b> ' + feature.properties.OPEN + '<br >' +
                        '<b>Limited:</b> ' + feature.properties.LIMITED  + '<br >' +
                        '<b>Route Type:</b> ' + feature.properties.ROUTE_TYPE + '<br >' +
                        '<b>Field Office:</b> ' + feature.properties.FIELD_OFC + '<br >' +
                        '<b>Subregion:</b> ' + feature.properties.SUBREGION  + '<br >' +
                        '<b>GPX:</b> ' + feature.properties.GPX + '<br >' +
                        '<b>KML:</b> ' + feature.properties.KML);
    					}
	   }).addTo(map);
  });

// sample geojson file:
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "GID": null, "NAME": "12N38", "OPEN": "Y", "LIMITED": "None", "ROUTE_TYPE": "Full Size","color":"#537F21","AGENCY": "USFS", "FIELD_OFC": "El Dorado NF", "PRIVATE": null, "ROUTE_DB": "USFS", "NEW_NAME": null, "SUBREGION": "Central Sierra Nevada", "GPX": "<a href=\"http:\/\/www.owlsheadgps.com\/downloads\/gpx\/central_sierra_nevada\/zip\/12n38.gpx.zip\">Click Here<\/a>", "KML": "<a href=\"http:\/\/www.owlsheadgps.com\/downloads\/kml\/central_sierra_nevada\/12n38.kml\">Click Here<\/a>" }, "geometry": { "type": "LineString", "coordinates": [...] } },

{ "type": "Feature", "properties": { "GID": null, "NAME": "12N38A", "OPEN": "Y", "LIMITED": "None", "ROUTE_TYPE": "Full Size", "color":"#537F21","AGENCY": "USFS", "FIELD_OFC": "El Dorado NF", "PRIVATE": null, "ROUTE_DB": "USFS", "NEW_NAME": null, "SUBREGION": "Central Sierra Nevada", "GPX": "<a href=\"http:\/\/www.owlsheadgps.com\/downloads\/gpx\/central_sierra_nevada\/zip\/12n38a.gpx.zip\">Click Here<\/a>", "KML": "<a href=\"http:\/\/www.owlsheadgps.com\/downloads\/kml\/central_sierra_nevada\/12n38a.kml\">Click Here<\/a>" }, "geometry": { "type": "LineString", "coordinates": [ ... ] } },

**Comment by leplatrem** [comment]
I believe you can't have two ’onEachFeature' entries in options.

This is not the best place to ask for support though, you might be luckier on stackoverflow...

Good luck!!

**Comment by fredericbonifas** [comment]
Hi @sundancemc 

You should merge the two *onEachFeature* options in the same:

```javascript
onEachFeature: function (feature, layer) {
    layer.setText(feature.properties.NAME);
    layer.bindPopup('<b>Name:</b> ' + feature.properties.NAME + '<br >' +
    ...
},
```

**Comment by sundancemc** [comment]
I get the following error when I do. 

[Error] TypeError: undefined is not a function (evaluating 'layer.setText(feature.properties.NAME)')
	onEachFeature (index.html, line 49)
	addData (leaflet.js, line 8)
	addData (leaflet.js, line 8)
	initialize (leaflet.js, line 8)
	e (leaflet.js, line 6)
	geoJson (leaflet.js, line 8)
	(anonymous function) (index.html, line 44)
	(anonymous function) (jquery-1.11.0.min.js, line 2)
	j (jquery-1.11.0.min.js, line 2)
	fireWith (jquery-1.11.0.min.js, line 2)
	x (jquery-1.11.0.min.js, line 4)
	b (jquery-1.11.0.min.js, line 4)
