### ISSUE TITLE
Text center should account for path orientation (i.e. vertical centering)

### ISSUE THREAD

**Issue by a1an77** [makinacorpus/Leaflet.TextPath#38]
If a path is south -> north oriented, the label does not get correctly centred as the centring seems to occur only on the W-E axis. For a "mostly vertical" feature the centre should be computed accounting for the (visible) vertical part of the path.

To sum up: 2D centre detection, then projected on the path to avoid "out of path" labelling (e.g. L shaped feature)

**Comment by leplatrem** [comment]
It looks like a duplicate of #33 

And there were submissions to fix that (#27, #31, #34).

Since I have absolutely no time to invest for this plugin, some help to review the propositions would be greatly appreciated :) For example providing some screenshots for different configurations/angles

**Comment by leplatrem** [comment]
Fixed by #34
