### ISSUE TITLE
Demo does not work with https (mixed content error)

### ISSUE THREAD

**Issue by araichev** [makinacorpus/Leaflet.TextPath#39]
Hi there, the TextPath demo at https://makinacorpus.github.io/Leaflet.TextPath/ does not work on my browser (Firefox 42.0), because the webpage has mixed content (HTTP and HTTPS calls).
Could you fix this by making all calls over HTTPS?

**Comment by leplatrem** [comment]
The link is without https  http://makinacorpus.github.io/Leaflet.TextPath/ 

Links to resources could be changed to fix that indeed.

**Comment by fredericbonifas** [comment]
I just changed the tiles URL to  `//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`
However, Leaflet CDN is not served over HTTPS.

So there still is a mixed content issue
