### ISSUE TITLE
Leaflet 1.0 compatible version?

### ISSUE THREAD

**Issue by ianpetzer** [makinacorpus/Leaflet.TextPath#53]
Hi,

Thanks for this awesome plugin. I was just wondering if anyone was working on a Leaflet 1.0 compatible version of this?

**Comment by klee500** [comment]
Switch to Branch [leaflet0.8-dev](https://github.com/makinacorpus/Leaflet.TextPath/tree/leaflet0.8-dev). It is compatible with Leaflet 1.0.1

**Comment by ianpetzer** [comment]
@klee500 Thanks so much. That is awesome.
