### ISSUE TITLE
Not compatible to the new leaflet 1.1.0 (Solved!!!)

### ISSUE THREAD

**Issue by banmtG** [makinacorpus/Leaflet.TextPath#56]
Dear developers,

Could you please update this so that it could be used with the new leaflet.js (1.1.0). It would be soooo great!!!.

Error from console: TypeError: L.Path.prototype._createElement is not a function[Learn More] when I used it with leaflet 1.1.0.

Thanks.

**Comment by RhinoDevel** [comment]
Did you use the leaflet0.8-dev branch? See [README.md](https://github.com/makinacorpus/Leaflet.TextPath/blob/gh-pages/README.md).

**Comment by banmtG** [comment]
Dear RhinoDevel,

Thank you very much for helping me.

I am not so sure how to use both Leaflet 1.1.0 and leaflet0.8-dev branch in one website. My current web uses leaflet 1.1.0 and its layers and functions (For example: L.tooltip) that were not available in previous leaflet versions. 

Maybe you can give me some hints?

All the best,

**Comment by RhinoDevel** [comment]
Take a look at the source of the [demo](http://makinacorpus.github.io/Leaflet.TextPath/). Replace `<script>` and `<link>` entries in `<head>` with Leaflet 1.1.0 and Leaflet.TextPath's leafleat0.8-dev.

**Comment by banmtG** [comment]
Thanks so muchhhhhh RhinoDevel.

Finally, with your patience and help, I am able to make it work. You saved my life!!!!

For those who are facing the same issue, please follow the steps below:

1. Download the source code here (leaflet0.8-dev) https://github.com/makinacorpus/Leaflet.TextPath/tree/leaflet0.8-dev.

2. Copy the leaflet.js and leaflet.css (those are 0.8 dev versions) and especially the leaflet.textpath.js at the root folder of the package to your project. You might need to change the names so that they wont replace your current leaflet (css and js) and leaflet.textpath. In my case, I just added 0.8 at the end of these files.

3. Include the 0.8 versions in your code. In my case, they are:

              `  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.1.0/dist/leaflet.css" />
		<script src="https://unpkg.com/leaflet@1.1.0/dist/leaflet.js"></script>
		<link rel="stylesheet" href="js/leaflet0.8.css" />
		<script src="js/leaflet0.8.js"></script>
		<script src="js/leaflet.textpath0.8.js"></script>`

So you can use the textpath with leaflet 1.1.0 and leaflet0.8 at the same time.

All credits go to RhinoDevel for his kind instruction.

Good luck to you all!

**Comment by RhinoDevel** [comment]
@banmtG Please close this issue.
