### ISSUE TITLE
Confused by versions

### ISSUE THREAD

**Issue by amosfolz** [makinacorpus/Leaflet.TextPath#75]
I am a bit confused by the branches and what version of leaflet they are supposed to be used for.

On branch `master` it states: "The version on the `gh-pages` branch targets Leaflet 1.3.1."

Then when you switch to the `gh-pages` branch it states: "The version on `the gh-pages` branch targets Leaflet 0.7.3."

**Comment by babastienne** [comment]
Fixed in last commit, the current targeted version on the demo is 1.3.1. It seems that the plugin is working with at least leaflet 1.6.0.
