### ISSUE TITLE
Option to choose repeat spacing

### ISSUE THREAD

**Issue by nekromoff** [makinacorpus/Leaflet.TextPath#95]
`repeat: true` now does continuous text repeat.

I wanted to have a repeat with some spacing between text elements.

My workaround was to add a condition to pad the text with a non-breakable space after line 81:
```
if (options.repeat!=true && options.repeat>=1) {
    text=text.padStart(options.repeat, '\u00A0');
}
```

Now I can do space separated repeat such as:
`repeat: 10` and get this (example):
![image](https://github.com/makinacorpus/Leaflet.TextPath/assets/8550349/984dd8eb-1583-43c8-89e7-c4e163d42272)

This improves map clutter cause by continuous repeat, e.g. it looked like this before:
![image](https://github.com/makinacorpus/Leaflet.TextPath/assets/8550349/848e0e30-6739-4d74-b48e-6a65688d39fd)

**Comment by babastienne** [comment]
Hello @nekromoff 

Thanks for reporting this issue. :pray: 

In fact, even in the demo on this repository we're using a trick (some space characters) to add some spacing between repeated text, as you can see here : https://github.com/makinacorpus/Leaflet.TextPath/blob/master/docs/example.html#L57

The solution used in the demo is definitely not the prettiest one and is more of a workaround. 

I like your suggestion, considering it's not breaking the current behavior and just adding some option to format the repeated text. Could you make a PR to add the feature you're using to the next version of this library ?

**Comment by nekromoff** [comment]
Will do, thanks.

**Comment by nekromoff** [comment]
https://github.com/makinacorpus/Leaflet.TextPath/pull/96
